[0m21:12:32.862853 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa93e4022d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa93f04d5b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa93ff64e00>]}


============================== 21:12:32.867823 | 672840f0-7e5c-41a7-b532-129308589820 ==============================
[0m21:12:32.867823 [info ] [MainThread]: Running with dbt=1.9.2
[0m21:12:32.868675 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/home/marcosmadeira/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init npl_data', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:12:32.879503 [debug] [MainThread]: Starter project path: /home/marcosmadeira/modern_data_pipeline/venv/lib/python3.12/site-packages/dbt/include/starter_project
[0m21:12:32.884096 [info ] [MainThread]: 
Your new dbt project "npl_data" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:12:32.885649 [info ] [MainThread]: Setting up your profile.
[0m21:12:32.887637 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m21:12:32.888738 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.1181439, "process_in_blocks": "0", "process_kernel_time": 0.172201, "process_mem_max_rss": "88072", "process_out_blocks": "64", "process_user_time": 1.377612}
[0m21:12:32.889308 [debug] [MainThread]: Command `dbt init` failed at 21:12:32.889163 after 0.12 seconds
[0m21:12:32.889764 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa93e8be8a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa93e454710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa93e875310>]}
[0m21:12:32.890265 [debug] [MainThread]: Flushing usage events
[0m21:12:33.807764 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:23:30.646373 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f799bcdcf80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f799b856ff0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f799b9f72f0>]}


============================== 13:23:30.675587 | 4cef503b-c45e-418f-9853-898a8d823df7 ==============================
[0m13:23:30.675587 [info ] [MainThread]: Running with dbt=1.9.2
[0m13:23:30.677137 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/home/marcosmadeira/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:23:30.714230 [info ] [MainThread]: dbt version: 1.9.2
[0m13:23:30.714946 [info ] [MainThread]: python version: 3.12.3
[0m13:23:30.715510 [info ] [MainThread]: python path: /home/marcosmadeira/modern_data_pipeline/venv/bin/python3
[0m13:23:30.715997 [info ] [MainThread]: os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
[0m13:23:30.722205 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.postgres'
[0m13:23:30.723064 [info ] [MainThread]: Using profiles dir at /home/marcosmadeira/.dbt
[0m13:23:30.723593 [info ] [MainThread]: Using profiles.yml file at /home/marcosmadeira/.dbt/profiles.yml
[0m13:23:30.724057 [info ] [MainThread]: Using dbt_project.yml file at /home/marcosmadeira/modern_data_pipeline/dags/dbt/dbt_project.yml
[0m13:23:30.724548 [info ] [MainThread]: Configuration:
[0m13:23:30.724980 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m13:23:30.725439 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:23:30.725865 [info ] [MainThread]: Required dependencies:
[0m13:23:30.726521 [debug] [MainThread]: Executing "git --help"
[0m13:23:30.729028 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:23:30.729600 [debug] [MainThread]: STDERR: "b''"
[0m13:23:30.730044 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:23:30.730576 [info ] [MainThread]: Connection test skipped since no profile was found
[0m13:23:30.731170 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:23:30.731606 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "modern_npl_data", target "dev" invalid: Runtime Error
    Could not find adapter type postgres!


[0m13:23:30.732046 [info ] [MainThread]: Project loading failed for the following reason:
 project path </home/marcosmadeira/modern_data_pipeline/dags/dbt/dbt_project.yml> not found

[0m13:23:30.733379 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.18428242, "process_in_blocks": "8", "process_kernel_time": 0.124356, "process_mem_max_rss": "88076", "process_out_blocks": "24", "process_user_time": 1.564813}
[0m13:23:30.734394 [debug] [MainThread]: Command `dbt debug` failed at 13:23:30.734088 after 0.19 seconds
[0m13:23:30.735022 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f799bd6fe90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f799afe4830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f799b212570>]}
[0m13:23:30.735581 [debug] [MainThread]: Flushing usage events
[0m13:23:32.273438 [debug] [MainThread]: An error was encountered while trying to flush usage events
